# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13b438a75a992be1238f837e50e04c8e96e19c105deae4ce614a719c9ebd72ad7fbab329405cff7cc93c1d470cc7e24faff1a2236e42cb950b50ba02c9b9d1d4

test:
  secret_key_base: 0bba95bd251b8ddf7dba2267e804441989526d06c5131a5082e83d769a1dbab91fd31e38d8bcd64217100280c0e85f70303a27f585f0f2084c714d160f5e62b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
